version: "3.0"

services:

  auth:
    build: .
    container_name: dicid_auth_dev
    env_file: .env
    environment:
      NODEID: "dicid-auth"
      SERVICES: auth
    volumes:
      - ../../microservices:/app
    command: /bin/sh -c "npm install --silent --progress=false && npm run dev"

  api:
    build: .
    container_name: dicid_api_dev
    env_file: .env
    environment:
      NODEID: "dicid-api"
      SERVICES: api
    ports:
      - 3000:3000
    volumes:
      - ../../microservices:/app
    command: /bin/sh -c "npm install --silent --progress=false && npm run dev"
 
  nats:
    image: nats

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: