version: "3.0"

services:

  border:
    build: .
    env_file: .env
    environment:
      SERVICES: border
    depends_on:
      - nats
    ports:
      - 3000:3000
    stop_signal: SIGINT
    restart: always

  auth:
    build: .
    env_file: .env
    environment:
      SERVICES: auth
    depends_on:
      - nats
      - mongo
    stop_signal: SIGINT
    restart: always

  user:
    build: .
    env_file: .env
    environment:
      SERVICES: user
    depends_on:
      - nats
      - mongo
    stop_signal: SIGINT
    restart: always

  nats:
    image: nats
    restart: always

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
    volumes:
      - production_mongodb_data:/data/db
    restart: always

volumes:
  production_mongodb_data:
